"""
Simple site diagram generator for a small static site.
Scans HTML files in the repo, extracts page titles and links between pages, and
renders a PNG diagram with boxes and arrows.

Usage:
  python scripts/generate_site_diagram.py

Produces: site-diagram.png at the repo root.

This script uses only the Python standard library and Pillow (PIL). Install with:
  python -m pip install Pillow
"""
from pathlib import Path
from html.parser import HTMLParser
from PIL import Image, ImageDraw, ImageFont
import re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'site-diagram.png'

class LinkParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []
        self.in_title = False
        self.title = None

    def handle_starttag(self, tag, attrs):
        if tag.lower() == 'a':
            href = dict(attrs).get('href')
            if href:
                self.links.append(href)
        if tag.lower() == 'title':
            self.in_title = True

    def handle_endtag(self, tag):
        if tag.lower() == 'title':
            self.in_title = False

    def handle_data(self, data):
        if self.in_title:
            if not self.title: self.title = data.strip()


def find_html_files(root):
    return sorted(root.glob('*.html'))


def parse_pages(files):
    pages = {}
    for f in files:
        text = f.read_text(encoding='utf-8', errors='ignore')
        p = LinkParser()
        p.feed(text)
        pages[f.name] = {
            'path': f,
            'title': p.title or f.name,
            'links': p.links,
        }
    return pages


def normalize_link(href):
    # keep only file name portion for local links
    if href.startswith('http://') or href.startswith('https://') or href.startswith('mailto:'):
        return None
    href = href.split('#')[0].split('?')[0]
    href = href.rstrip('/')
    if not href:
        return None
    return Path(href).name


def build_graph(pages):
    nodes = list(pages.keys())
    edges = []
    for name, info in pages.items():
        for raw in info['links']:
            target = normalize_link(raw)
            if target and target in pages:
                edges.append((name, target))
    return nodes, edges


def layout_nodes(nodes, width, height, margin=40):
    # simple grid layout
    cols = max(1, int((len(nodes))**0.5 + 0.0001))
    rows = (len(nodes) + cols - 1) // cols
    cell_w = (width - 2*margin) // cols
    cell_h = (height - 2*margin) // rows
    pos = {}
    for i, n in enumerate(nodes):
        r = i // cols
        c = i % cols
        x = margin + c*cell_w + cell_w//2
        y = margin + r*cell_h + cell_h//2
        pos[n] = (x, y)
    return pos


def draw_diagram(nodes, edges, pages):
    W, H = 1200, 800
    img = Image.new('RGBA', (W, H), 'white')
    draw = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype('arial.ttf', 14)
        title_font = ImageFont.truetype('arialbd.ttf', 16)
    except Exception:
        font = ImageFont.load_default()
        title_font = font

    pos = layout_nodes(nodes, W, H)
    box_w, box_h = 220, 60

    # draw edges
    for a, b in edges:
        ax, ay = pos[a]
        bx, by = pos[b]
        draw.line((ax, ay, bx, by), fill='gray', width=2)
        # arrowhead
        dx = bx - ax
        dy = by - ay
        dist = max((dx*dx+dy*dy)**0.5, 1)
        ux, uy = dx/dist, dy/dist
        # two points for arrow
        left = (bx - ux*12 - uy*6, by - uy*12 + ux*6)
        right = (bx - ux*12 + uy*6, by - uy*12 - ux*6)
        draw.polygon([ (bx,by), left, right ], fill='gray')

    # draw nodes
    for n in nodes:
        x,y = pos[n]
        left = x - box_w//2
        top = y - box_h//2
        right = x + box_w//2
        bottom = y + box_h//2
        draw.rectangle([left, top, right, bottom], outline='black', width=2, fill='#f7f7ff')
        title = pages[n]['title']
        name = n
        tw, th = draw.textsize(title, font=title_font)
        nw, nh = draw.textsize(name, font=font)
        draw.text((x - tw/2, top + 8), title, fill='black', font=title_font)
        draw.text((x - nw/2, top + 8 + th + 4), name, fill='black', font=font)

    # footer
    draw.text((10, H-20), 'Generated by generate_site_diagram.py', fill='black', font=font)
    img.save(OUT)
    return OUT


def main():
    html_files = find_html_files(ROOT)
    pages = parse_pages(html_files)
    nodes, edges = build_graph(pages)

    if not nodes:
        print('No HTML files found.')
        return

    out = draw_diagram(nodes, edges, pages)
    print('Wrote', out)

if __name__ == '__main__':
    main()
